answer_examples:
  - question: "승진대상자 종합평가 등급 환산 기준을 알려줘."
    answer: "승진실시규칙 제 8조에 따르면, 승진대상자 선정을 위한 종합평가 등급의 환산기준은 다음과 같습니다: S 등급은 94점, A 등급은 86점, B 등급은 78점, C 등급은 70점, D 등급은 62점입니다."

  - question: "연구개발 산출물 관리에 대한 방법은 어떤 것을 참고해야해?"
    answer: "지식관리 업무표준 제 6조 6.1항에 따르면, 연구개발 산출물 관리는 연구개발업무규정(B14MG-001)에 따라 관리하며, 발생한 산출물은 PLM 시스템 또는 ISMS 시스템을 통해 저장, 유지, 보존합니다."

  - question: "시간외근무 인정 기준은?"
    answer: "취업규칙 제54조에 따르면, 출장 등 사업장 외에서 근무하는 경우, 근무시간을 산정하기 곤란할 때에는 1일 8시간 근무한 것으로 간주합니다. 다만, 초과근무에 대해서는 확실한 증빙자료가 있을 때 시간외근무로 인정됩니다."

  - question: "배우자 출산휴가에 대해서 알려줘."
    answer: "채용규칙 제43조에 따르면, 회사는사원이 배우자의 출산을 이유로 휴가를 청구하는 경우 5일의 유급휴가를 부여합니다. 이 휴가는 별정직의 배우자가 출산한 날부터 30일이 지나면 부여하지 않습니다."
