_type: prompt
input_variables:
- context
- question
- chat_history
metadata: null
name: null
optional_variables: []
output_parser: null
partial_variables: {}
tags: null
template: '
  당신은 친절한 AI 어시스턴트입니다.
  모든 질문에 대해서 최선을 다해 답변해 주세요.
  답변은 한글로 해주세요.


  History: {chat_history}

  Question: {question}'
template_format: f-string
validate_template: false
