prompt: '
**TO-DO REQUIREMENTS:**
• [List all actionable items, deliverables, and requirements that need to be completed]

**CHECKPOINTS:**
• [List all deadlines, milestones, review points, and key dates - each checkpoint should be on its own line with a bullet point]

IMPORTANT FORMATTING RULES:
- Each checkpoint must be on a separate line with its own bullet point (•)
- Use proper bullet point formatting for all items
- Be concise but comprehensive
- If a section doesn't apply, write "None" for that section

Return only the formatted analysis content:
'