#!/usr/bin/env python3
"""
Environment Setup Helper for IntraSeek
This script helps you set up the required environment variables.
"""

import os
from pathlib import Path

def create_env_file():
    """Create a .env file with OpenAI configuration"""
    
    env_path = Path(".env")
    
    if env_path.exists():
        print("⚠️  .env file already exists!")
        response = input("Do you want to overwrite it? (y/N): ")
        if response.lower() != 'y':
            print("❌ Setup cancelled.")
            return
    
    print("🔧 Setting up environment variables for IntraSeek...")
    print()
    
    # Get OpenAI API key
    print("📝 OpenAI Configuration:")
    openai_key = input("Enter your OpenAI API key (or press Enter to skip): ").strip()
    
    if openai_key:
        print("✅ OpenAI API key provided")
        embedding_model = "text-embedding-3-large"
        llm_model = "gpt-4o"
    else:
        print("⚠️  No OpenAI API key provided, will use Ollama defaults")
        embedding_model = "nomic-embed-text"
        llm_model = "gemma2:9b"
    
    # Get Ollama URL
    print()
    print("🔄 Ollama Configuration:")
    ollama_url = input("Enter Ollama base URL (default: http://localhost:11434): ").strip()
    if not ollama_url:
        ollama_url = "http://localhost:11434"
    
    # Create .env content
    env_content = f"""# IntraSeek Environment Configuration
# Generated by setup_env.py

# LLM Configuration
SELECTED_LLM={llm_model}

# Embedding Model Configuration
SELECTED_EMBEDDING={embedding_model}

# Ollama Configuration
OLLAMA_BASE_URL={ollama_url}
"""
    
    if openai_key:
        env_content += f"""
# OpenAI Configuration
OPENAI_API_KEY={openai_key}
"""
    
    # Write .env file
    with open(env_path, 'w') as f:
        f.write(env_content)
    
    print()
    print("✅ .env file created successfully!")
    print()
    print("📋 Configuration Summary:")
    print(f"   LLM Model: {llm_model}")
    print(f"   Embedding Model: {embedding_model}")
    print(f"   Ollama URL: {ollama_url}")
    if openai_key:
        print(f"   OpenAI API Key: {'*' * (len(openai_key) - 4) + openai_key[-4:]}")
    print()
    print("🚀 You can now run: streamlit run app.py")

if __name__ == "__main__":
    create_env_file()
